# backend/docker-compose.yml
version: '3.8'

services:
  api:
    build: .
    ports:
      - "6000:6000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=${mongodb+srv://dushyant4665:dcBDGKDEY8XcLjuH@cluster0.ysvvv.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0}
      - GEMINI_API_KEY=${AIzaSyC6rKRy6EL29o3Z7sszR1u_LY-lgL9k5jQ}
      - OPENAI_API_KEY=${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}
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: